/* eslint-disable @typescript-eslint/no-explicit-any, prefer-const, @typescript-eslint/no-unused-vars */
import React, { useState } from 'react';
import { Download, Copy, Check, FileCode, FileSpreadsheet, ShieldCheck } from 'lucide-react';
import { CleansedRecord, GovernanceDictionary, QualityMetrics } from '../types';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  cleansedRecords: CleansedRecord[];
  dictionary: GovernanceDictionary;
  metrics: QualityMetrics;
}

export const ExportModal: React.FC<ExportModalProps> = ({
  isOpen,
  onClose,
  cleansedRecords,
  dictionary,
  metrics
}) => {
  const [copied, setCopied] = useState(false);
  const [exportFormat, setExportFormat] = useState<'csv' | 'json' | 'report'>('csv');

  if (!isOpen) return null;

  // Convert cleansed records to CSV
  const generateCsv = (): string => {
    const headers = dictionary.rules.map(r => r.targetColumnName);
    const headerLine = headers.join(',');

    const rowLines = cleansedRecords.map(rec => {
      return headers
        .map(h => {
          const val = rec[h] !== undefined && rec[h] !== null ? String(rec[h]) : '';
          return `"${val.replace(/"/g, '""')}"`;
        })
        .join(',');
    });

    return [headerLine, ...rowLines].join('\n');
  };

  // Convert to JSON without internal underscore props
  const generateCleanJson = (): string => {
    const headers = dictionary.rules.map(r => r.targetColumnName);
    const cleanList = cleansedRecords.map(rec => {
      const item: Record<string, any> = {};
      headers.forEach(h => {
        item[h] = rec[h];
      });
      return item;
    });
    return JSON.stringify(cleanList, null, 2);
  };

  // Generate Governance Audit Report
  const generateAuditReport = (): string => {
    return `# DATA GOVERNANCE COMPLIANCE & CLEANSING AUDIT REPORT
Audit Date: ${new Date().toLocaleDateString('en-US')}
Policy Standard: ${dictionary.name}

## 1. Quality Scorecard
- Overall Governance Score: ${metrics.overallScore}%
- Completeness: ${metrics.completeness}%
- Validity: ${metrics.validity}%
- Uniqueness: ${metrics.uniqueness}%
- Accuracy: ${metrics.accuracy}%
- Consistency: ${metrics.consistency}%

## 2. Processing & Cleansing Metrics
- Total Processed Rows: ${metrics.totalRows}
- Total Modified/Imputed Cells: ${metrics.modifiedCellCount}
- Duplicate Rows Flagged/Handled: ${metrics.duplicateCount}
- Quality Anomalies Detected: ${metrics.errorCount}

## 3. Enforced Ruleset Dictionary
${dictionary.rules.map(r => `- [${r.targetColumnName.toUpperCase()}] Type: ${r.dataType} | Casing: ${r.casing} | Required: ${r.isRequired}`).join('\n')}

---
Generated by Data Governance & Cleansing Engine.
`;
  };

  const getContent = () => {
    if (exportFormat === 'csv') return generateCsv();
    if (exportFormat === 'json') return generateCleanJson();
    return generateAuditReport();
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(getContent());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const text = getContent();
    const ext = exportFormat === 'csv' ? 'csv' : exportFormat === 'json' ? 'json' : 'md';
    const mime = exportFormat === 'json' ? 'application/json' : 'text/plain';

    const blob = new Blob([text], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `data_cleansed_governance_${Date.now()}.${ext}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4">
      <div className="bg-white border border-slate-200 rounded-lg max-w-2xl w-full p-5 shadow-lg space-y-3">
        
        {/* Header */}
        <div className="flex items-center justify-between pb-2.5 border-b border-slate-200">
          <div className="flex items-center space-x-2">
            <Download className="w-4 h-4 text-emerald-600" />
            <h3 className="font-bold text-sm text-slate-900">
              Export Cleansed Dataset & Governance Report
            </h3>
          </div>
          <button
            onClick={onClose}
            className="text-slate-400 hover:text-slate-700 font-bold p-1 rounded hover:bg-slate-100 transition-colors cursor-pointer"
          >
            ✕
          </button>
        </div>

        {/* Format Selector */}
        <div className="grid grid-cols-3 gap-1.5 p-1 bg-slate-100 rounded-md text-xs">
          <button
            onClick={() => setExportFormat('csv')}
            className={`py-1.5 px-2 rounded font-semibold flex items-center justify-center space-x-1 transition-all ${
              exportFormat === 'csv' ? 'bg-white text-emerald-700 shadow-xs font-bold' : 'text-slate-600'
            }`}
          >
            <FileSpreadsheet className="w-3.5 h-3.5" />
            <span>CSV Format</span>
          </button>
          <button
            onClick={() => setExportFormat('json')}
            className={`py-1.5 px-2 rounded font-semibold flex items-center justify-center space-x-1 transition-all ${
              exportFormat === 'json' ? 'bg-white text-indigo-700 shadow-xs font-bold' : 'text-slate-600'
            }`}
          >
            <FileCode className="w-3.5 h-3.5" />
            <span>JSON Format</span>
          </button>
          <button
            onClick={() => setExportFormat('report')}
            className={`py-1.5 px-2 rounded font-semibold flex items-center justify-center space-x-1 transition-all ${
              exportFormat === 'report' ? 'bg-white text-purple-700 shadow-xs font-bold' : 'text-slate-600'
            }`}
          >
            <ShieldCheck className="w-3.5 h-3.5" />
            <span>Audit Report</span>
          </button>
        </div>

        {/* Code Preview */}
        <div className="relative">
          <pre className="bg-slate-900 text-slate-100 p-3 rounded-md text-[11px] font-mono max-h-60 overflow-auto border border-slate-700 leading-relaxed whitespace-pre-wrap">
            {getContent()}
          </pre>
        </div>

        {/* Footer Actions */}
        <div className="pt-2.5 border-t border-slate-200 flex justify-between items-center">
          <button
            onClick={onClose}
            className="px-3 py-1.5 rounded-md text-xs font-semibold text-slate-600 hover:bg-slate-100 cursor-pointer"
          >
            Cancel
          </button>

          <div className="flex items-center space-x-2">
            <button
              onClick={handleCopy}
              className="px-3 py-1.5 rounded-md bg-slate-100 hover:bg-slate-200 text-slate-800 text-xs font-semibold flex items-center space-x-1 transition-all cursor-pointer"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied!' : 'Copy to Clipboard'}</span>
            </button>

            <button
              onClick={handleDownload}
              className="px-4 py-1.5 rounded-md bg-emerald-600 hover:bg-emerald-700 text-white font-semibold text-xs shadow-xs flex items-center space-x-1 cursor-pointer"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download File</span>
            </button>
          </div>
        </div>

      </div>
    </div>
  );
};
